### ISSUE TITLE
For CONS under decentralized topology, are forwarding rules sets not an option?

### ISSUE THREAD

**Issue by patilpappmodz1** [paolosalvatori/private-endpoints-topologies#10]
Under the cons for Decentralized approach, it is stated that custom dns servers are required and it states "This requirement is necessary because the Azure-provided DNS and Private DNS Zones do not support DNS forwarding and conditional forwarding." - Are forwarding rulesets and associated links not an option here ?

**Comment by paolosalvatori** [comment]
Hi @patilpappmodz1, this article was created in early 2020. [Azure DNS Private Resolver](https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-overview) was introduced in 2023.

**Comment by patilpappmodz1** [comment]
oh ok. thanks for clarifying.
