### ISSUE TITLE
image1 has an error on step 5 of the DNS Resolution flow

### ISSUE THREAD

**Issue by oramoss** [paolosalvatori/private-endpoints-topologies#2]
I think there is a slight mistake on image1...

The image shows step 5 going via private endpoint 10.0.0.6 (for abc.dfs.core.windows.net) but the words for step 5 (correctly) state it's going via 10.0.0.5 to get to xyz.blob.core.windows.net.

**Comment by paolosalvatori** [comment]
Thanks, you are right, I'll move label 5 to the other private endpoint 😃

**Comment by oramoss** [comment]
No problem...it was a while ago that I read it but I think there may have been similar issues with the other diagrams and their associated numbers so you might want to check them all.

**Comment by paolosalvatori** [comment]
Yes, I'm pretty sure that other diagrams will have the same issue :)

**Comment by oramoss** [comment]
Great article though - bravo!

**Comment by paolosalvatori** [comment]
Thanks :)
