### ISSUE TITLE
Storage Account Private DNS policy not finding resources

### ISSUE THREAD

**Issue by jantorep** [paolosalvatori/private-endpoints-topologies#4]
Hello

I tried both of the json templates for deploying a private DNS sone for storage accounts in my tenant. But it seems to not find any resources. I pointed it to the right Private DNS sone that is created. 

The first one is not finding any resources. The 2nd fails saying it can't find the private dns sone id.

I have updated the config as far as i can see to the correct values. But im not a policy or json expert so id apriciate some help.

I have tried using the built-in policy that was used for service bus and key vault. But that only picks up those resources.

Thanks
Jan-Tore

**Comment by paolosalvatori** [comment]
@jantorep with JSON template, do you mean the JSON templates to create policies? Which in particular did you try to deploy? Did you have problems deploying the Azure Policy definitions or assignments? I need more info to understand your problem.

**Comment by paolosalvatori** [comment]
It's not enough to create definitions, you also need to make assignments at the management group, subscription, resource group scope.+
