### ISSUE TITLE
Links have probably unintended URL redirection via nam06.safelinks.protection.outlook.com

### ISSUE THREAD

**Issue by zioproto** [paolosalvatori/private-endpoints-topologies#6]
Thanks for the interesting document. I found a couple of links that probably should point directly to docs.microsoft.com.

https://github.com/paolosalvatori/private-endpoints-topologies/blob/a8d74a4bfbba12eb7daf4f67ce2223c858f601ba/README.md?plain=1#L248

https://github.com/paolosalvatori/private-endpoints-topologies/blob/a8d74a4bfbba12eb7daf4f67ce2223c858f601ba/README.md?plain=1#L280

**Comment by paolosalvatori** [comment]
Fixed thanks 😸
