### ISSUE TITLE
Some minor broken link for the private endpoint resource template

### ISSUE THREAD

**Issue by DavideDelVecchio** [paolosalvatori/private-endpoints-topologies#8]
Hi Paolo,
probably some resources were moved and this results on a broken link 
here 
https://github.com/paolosalvatori/private-endpoints-topologies#samples
I thin they should point to something like this 
https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.documentdb/cosmosdb-private-endpoint

**Comment by paolosalvatori** [comment]
Thanks @DavideDelVecchio I fixed all the broken links.
